// @weawr/engine — the team: lifecycle, commands and observations, with injected dependencies.
export { TeamEngine, PINNED_POLICY, defaultGit, policyOf, trackerBanner, watchLabel } from './team.js';
export type { EngineOptions, EngineHooks, GitRunner, RegistrationTarget } from './team.js';
export { DEFAULTS, EVENTS, configStamp, expandConfigPath, loadConfig, loadEnvFiles, pluginSpecs, templateOrigin } from './config.js';
export { EMPTY_REGISTRY, PLUGIN_API, loadPlugins, parseEvery, resolvePlugin } from './plugins.js';
export type { LoadedPlugin, PluginModule, PluginRegistry, PluginSources, PluginSpec, RolePreset, ScheduledTask, TaskContext } from './plugins.js';
export type { ConfigSources, TeamConfig, Rule } from './config.js';
export { briefVars, passLine, renderBrief } from './brief.js';
export { teamPaths, findRepoRoot, shortHash, userDir } from './paths.js';
export type { TeamPaths } from './paths.js';
export { agentNameFor, attemptId, teamId, hostId, roleRunId, taskId, trackerScope } from './identity.js';
export type { Identities } from './identity.js';
export { JsonStateStore, readJson, writeJsonAtomic } from './state.js';
export type { TeamState, StateStore, NudgeEntry } from './state.js';
export { acquireOwnership, currentOwner, describeHolder, processStartedAt, readCard } from './ownership.js';
export type { AcquireResult, OwnerCard, Ownership } from './ownership.js';
export { isStale, listRegistrations, readLegacyRegistry, registrationsDir, removeRegistration, writeRegistration } from './registration.js';
export type { Registration } from './registration.js';
export { ApplicationError, createApplication, resetTargets } from './application.js';
export type { Application, Command, CommandResult } from './application.js';
export { SqliteStore, UnsupportedSchemaError, SCHEMA_VERSION, storePath } from './store/sqlite.js';
export type { AttemptRecord, EventRecord, OperationRecord, PendingAction, Acknowledgement } from './store/sqlite.js';
export { inventory, migrateLegacyState } from './store/migrate.js';
export type { Inventory, MigrationResult } from './store/migrate.js';
export { isDurable, openOwnerStore, readTeamState, storeStatus } from './store/index.js';
export { teamView, humanWaitMs, indexSnapshot, ownsPr, production, productionWindows, runState, segments, timelineOf, watchWorkspaces, SETTLE_MS } from './projection.js';
export type { HerdrIndex, ProjectionInput, TimelineEvent } from './projection.js';
export { projectOffline } from './offline.js';
export { Enricher } from './enrich.js';
export { HERDR_AWAY, closeTask, exitRun, markDone, stopTask, tailTask, tidy, undoDone } from './actions.js';
export type { StoreKind } from './store/index.js';
export { COORDINATOR, agentOf, cell, coordinator, roleByline, table } from './comments.js';
